apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging_app_deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging_app
  template:
    metadata:
      labels:
        app: messaging_app
    spec:
      containers:
      - name: messaging_app_container
        image: fatonoh/messaging_app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: messaging_app_service
spec:
  type: ClusterIP
  selector:
    app: messaging_app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
